#pragma once

#include <format>
#include <string>
#include <vector>

/*
 * PlusargsBuilder
 *
 * Builds argc/argv command line to pass to
 * Verilated::getCommandArgs for the purpose
 * of passing plusargs to the verilated model.
 *
 * Plusargs generated by this have the format
 * "+<key>=<value>".
 *
 * Uses the Builder pattern.
 *
 * TODO: Function to allow custom format,
 * other than +<key>=<value>?
 */


class Argv {
private:
    std::vector<std::string> strings_;
    std::vector<char *> argv_;
public:
    explicit Argv(std::vector<std::string> strings) : strings_(std::move(strings)) {
        for(auto& str : strings_) {
            argv_.push_back(str.data());
        }
    }

    char **data() { return argv_.data(); }
    int size() const { return static_cast<int>(argv_.size()); };
};

class PlusargsBuilder {
private:
    std::vector<std::string> args_;
public:
    PlusargsBuilder() = default;

    PlusargsBuilder& addOption(const std::string& key, const auto& value) {
        args_.push_back(std::format("+{}={}", key, value));
        return *this;
    }

    PlusargsBuilder& addFlag(const std::string& key) {
        args_.push_back(std::format("+{}", key));
        return *this;
    }

    PlusargsBuilder& addCustom(const std::string& format_str, const auto&... args) {
        args_.push_back(std::format(format_str, args...));
        return *this;
    }

    Argv build() {
        return Argv{std::move(args_)};
    }
};
