import yaml
import sys
import os
import argparse

help_string = """
Setup synthesis files using FuseSoC outputs.
To test with aftx07, clone the synopsys flow repository:

```
git clone org-726@github.itap.purdue.edu:SoCETOrganization/synopsys-tsmc180.git
```

!!! You may not have access if you did not sign the tsmc180 NDA (and even if you did) !!!
If you need access email heint@purdue.edu with a copy of your NDA.

Once you have run cloned, find where it loads in filelist.tcl and adjust the path to the one you created
with this script. Then load fusioncompiler and run from the root of the repository:

```
fc_shell -file ./scripts/syn.tcl
```

Usage notes:
    - This script expects to be run from the directory above the FuseSoC
      'build' directory, running from anywhere else may not work as expected.

    - Use a .eda.yml file generated from running FuseSoC simulation with the
      '--no-export' flag. This script has not been tested without that flag,
      and may not work as expected!

"""

print(help_string)
parser = argparse.ArgumentParser(description='Generate synthesis files from FuseSoC outputs')
parser.add_argument('filename', type=str, help='path to .eda.yml file generated by FuseSoC to process')
args = parser.parse_args()


with open(args.filename) as fp:
    eda = yaml.safe_load(fp)


inc_dirs = []
inc_lines = []
src_lines = []
inc_lines_lec = []
src_lines_lec = []

for item in eda['files']:
    path = item['name']

    if ('tb' in path and "btb" not in path) or 'verification' in path or 'top_core' in path or 'sram_sim' in path:
        print("Warning: Skipping file {} since it looks like a TB or unsynthesizable verification IP.".format(path))
        continue
    
    # trim off leading ../ in path
    while path.startswith('../'):
        path = path[3:]
    
    path = os.path.abspath(path)

    if "/AFT-dev/spi/include/apb_if.vh" in path:
        continue

    # for list of files for synopsys to read
    if ".sv" in path and ".svh" not in path:
        prepend_str = 'analyze -format sverilog -define { NOIP SYNTHESIS SRAM } '
        src_lines.append(prepend_str + path + '\n')
    elif ".v" in path and ".vh" not in path:
        prepend_str = 'analyze -format verilog -define { NOIP SYNTHESIS SRAM } '
        src_lines.append(prepend_str + path + '\n')

    if ".vh" not in path:
        prepend_str = 'read_sverilog -r -define { NOIP SYNTHESIS SRAM } '
        src_lines_lec.append(prepend_str + path + '\n')

    # for list of filepaths 
    if 'is_include_file' in item.keys():
        path = os.path.dirname(path)
        if path not in inc_dirs:
            inc_dirs.append(path)
            prepend_str = 'lappend search_path '
            inc_lines.append(prepend_str + '"' + path + '"\n')
            inc_lines_lec.append(prepend_str + '"' + path + '"\n')


out_lines = inc_lines + src_lines
out_lines_lec = inc_lines_lec + src_lines_lec

#for line in out_lines:
#    print(line)

with open('filelist.tcl', 'w') as fp:
    fp.writelines(out_lines)
    fp.close()

with open('filelist.lec.tcl', 'w') as fp:
    fp.writelines(out_lines_lec)
    fp.close()