/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "synth_out/converted.v:1.1-17.10" *)
module counter(clk, rst_n, en, count);
  (* force_downto = 32'd1 *)
  (* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "7" *)
  wire [7:0] _00_;
  (* force_downto = 32'd1 *)
  (* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [7:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _02_;
  (* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _03_;
  (* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _04_;
  (* src = "synth_out/converted.v:8.13-8.16" *)
  input clk;
  wire clk;
  (* src = "synth_out/converted.v:11.27-11.32" *)
  output [7:0] count;
  reg [7:0] count;
  (* src = "synth_out/converted.v:10.13-10.15" *)
  input en;
  wire en;
  (* src = "synth_out/converted.v:9.13-9.18" *)
  input rst_n;
  wire rst_n;
  (* src = "synth_out/converted.v:12.2-16.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[0] <= 1'h0;
    else if (en) count[0] <= _01_[0];
  (* src = "synth_out/converted.v:12.2-16.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[1] <= 1'h0;
    else if (en) count[1] <= _02_[1];
  (* src = "synth_out/converted.v:12.2-16.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[2] <= 1'h0;
    else if (en) count[2] <= _02_[2];
  (* src = "synth_out/converted.v:12.2-16.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[3] <= 1'h0;
    else if (en) count[3] <= _02_[3];
  (* src = "synth_out/converted.v:12.2-16.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[4] <= 1'h0;
    else if (en) count[4] <= _02_[4];
  (* src = "synth_out/converted.v:12.2-16.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[5] <= 1'h0;
    else if (en) count[5] <= _02_[5];
  (* src = "synth_out/converted.v:12.2-16.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[6] <= 1'h0;
    else if (en) count[6] <= _02_[6];
  (* src = "synth_out/converted.v:12.2-16.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[7] <= 1'h0;
    else if (en) count[7] <= _02_[7];
  assign _01_[0] = ~(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) count[0];
  assign _02_[1] = count[1] ^(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  count[0];
  assign _02_[2] = count[2] ^(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[1];
  assign _02_[3] = count[3] ^(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[2];
  assign _02_[4] = count[4] ^(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[3];
  assign _02_[5] = count[5] ^(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[4];
  assign _02_[6] = count[6] ^(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[5];
  assign _02_[7] = count[7] ^(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[6];
  assign _00_[1] = count[1] &(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  count[0];
  assign _00_[3] = _03_ &(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _00_[1];
  assign _03_ = count[3] &(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  count[2];
  assign _04_ = count[5] &(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  count[4];
  assign _00_[5] = _04_ &(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[3];
  assign _00_[2] = count[2] &(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[1];
  assign _00_[4] = count[4] &(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[3];
  assign _00_[6] = count[6] &(* src = "synth_out/converted.v:16.13-16.25|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[5];
  assign _00_[0] = count[0];
  assign _01_[7:1] = count[7:1];
  assign _02_[0] = _01_[0];
endmodule
