`include "spi_type_pkg.vh"
`include "spi_if.vh"

//TODO: Controller redo. It is not even close to correct right now.

module spi_wrapper
(
    input logic CLK, nRST,
    //apb_if.apb_s apbif,
    bus_protocol_if.peripheral_vital busif,
    spi_if.spi	spiif
);
    import spi_type_pkg::*;

    /* Parameter Reference
    localparam NUM_REGS = 6;

    localparam SPICR1 = 0;
    localparam SPIBL = 1;
    localparam SPIBR = 2;
    localparam SPITDR = 3;
    localparam SPIRDR = 4;
    localparam SPISR = 5;

    //control register 1
    localparam SPIE = 31;
    localparam SPE = 30;
    localparam MSTR = 29;
    localparam CPOL = 28;
    localparam CPHA = 27;
    localparam SSOE = 26;
    localparam LSBFE = 25;
    localparam MODFEN = 24;
    localparam SPIBWM = 23;	//SPI buffer water mark level 23:20

    //status register
    localparam SPITF = 31;	//Transfer Complete
    localparam SPIRF = 30;	//Recieve Complete
    localparam SPIBWF = 29;	//Buffer Watermark Hit
    localparam SPIBF = 28;	//Buffer Full
    localparam SPIBE = 27;	//Transfer Buffer Empty
    localparam MODF = 26;	
    */

    localparam CONTROL_REG = 0;
    localparam BUFFER_LEN_REG = 1;
    localparam BAUD_REG = 2;
    localparam TX_DATA_REG = 3;
    localparam RX_DATA_REG = 4;
    localparam STATUS_REG = 5;

    // SPI Registers
    spi_cr_t control_reg, control_reg_n;
    spi_status_t status_reg, status_reg_n;
    logic [31:0] baud_rate_reg, baud_rate_reg_n;
    logic [31:0] byte_length_reg, byte_length_reg_n;

    logic EN;
    logic nEN;
    logic [NUM_REGS-1:0] r_enable;
    logic [NUM_REGS-1:0] w_enable;
    logic [NUM_REGS-1:0] r_en;
    logic [NUM_REGS-1:0] w_en;
    logic [NUM_REGS-1:0] addr_match;

    logic buffer_full, buffer_empty, buffer_half, OPC, MODF_flag, interrupt_out;
    logic [5:0] interrupt_clear;

    logic SCLK;		//clock generated by CG
    logic SCK_unedged;	//clock to edge detect
    logic SCLK_OUT;		//for output and to shift register
    logic SS_OUT;

    logic shift_enable, load_enable;
    logic serial_in, serial_out;	
    logic [7:0] parallel_in; //Connects the transmit FIFO to the transmit shift register.
    logic [7:0] parallel_out; //Connects the receive shift register to the receive FIFO.

    logic count_enable, cnt_clear, w_done;

    logic shifter_rst;
    logic Tx_REN, Rx_WEN;

    logic fifo_WEN, fifo_REN;
    logic [7:0] fifo_wdata;
    logic [7:0] fifo_rx_rdata; //Connects the receive FIFO's output to the SPI Recieve Data Register.
    logic [3:0] buff_tx_numdata, buff_rx_numdata; //Max of 10
    logic sck_in_posedge, sck_in_negedge, sck_out_posedge, sck_out_negedge;
    logic retime, sample, data_advance;
    logic MOSI_IN_sync, MISO_IN_sync, SS_IN_sync, SCK_IN_sync;
    logic start_retime;

    word_t apb_data;
    assign apb_data = busif.wdata;

    /*APB_SlaveInterface #(
        .NUM_REGS(NUM_REGS),
        .ADDR_OFFSET(0)
    ) apb
    (
        .clk(CLK), 
        .n_rst(nRST),

        //Inputs from APB Bridge
        .PADDR(apbif.PADDR),
        .PWDATA(apbif.PWDATA),
        .PENABLE(apbif.PENABLE),
        .PWRITE(apbif.PWRITE),
        .PSEL(apbif.PSEL),

        //Output to APB Bridge
        .PRDATA(apbif.PRDATA),

        //Input Data from Slave Registers
        .read_data({status_reg, 24'b0, fifo_rx_rdata, 32'b0, baud_rate_reg, byte_length_reg, control_reg}), //Routes the output of the SPI's internal registers and the recieve FIFO's output to the APB Slave Interface read data port.

        //Outputs to Slave Registers
        .w_enable(w_enable),
        .r_enable(r_enable),
        .w_data(apb_data)
    );*/

    // Do I need to connect these to anything?
	assign busif.error = 1'b0;
    assign busif.request_stall = 1'b0;

	genvar i;
	generate
        for(i = 0; i < NUM_REGS; i++) begin : w_r_enble_reg
            assign addr_match[i] = (busif.addr == i*4);
            assign w_enable[i] = (busif.wen && addr_match[i]);
            assign r_enable[i] = (busif.ren && addr_match[i]);
        end
    endgenerate

    always_comb begin : reg_read
		busif.rdata = '0;
		casez (r_enable)
			1: busif.rdata = control_reg;
			2: busif.rdata = byte_length_reg;
			4: busif.rdata = baud_rate_reg;
			8: busif.rdata = 32'b0; //TX_DATA_REG
			16: busif.rdata = {24'b0, fifo_rx_rdata};
			32: busif.rdata = status_reg;
		endcase
	end

    interrupt_control IC (
        .CLK(CLK), 
        .nRST(nRST),
        //interrupt types
        .rx_full(buffer_rx_full),
        .tx_empty(buffer_tx_empty),
        .rx_water(buffer_rx_half),
        .tx_water(buffer_tx_half),
        .transfer_complete(OPC),
        .modf(status_reg.modf),
        .clear(interrupt_clear),
        .interrupt_enable(control_reg.interrupt_enable),
        .interrupts(spiif.interrupts)
    );

    clock_generator CG
    (
        .CLK(CLK), 
        .nRST(nRST),
        // Baud rate register is one less than the effective clock divider
        .enable(control_reg.mode & count_enable),
        .polarity(control_reg.clock_polarity),
        .divider(baud_rate_reg + 32'd1),
        .SCK(SCLK)
    );


    edge_detect_spi POSEDGE_OUT
    (
        .clk(CLK),
        .n_rst(nRST),
        .edge_mode('1), //1 active high 0 active low
        .d_plus(SCLK),
        .d_edge(sck_out_posedge)
    );

    edge_detect_spi NEGEDGE_OUT
    (
        .clk(CLK),
        .n_rst(nRST),
        .edge_mode('0),
        .d_plus(SCLK),
        .d_edge(sck_out_negedge)
    );
    
    edge_detect_spi POSEDGE_IN
    (
        .clk(CLK),
        .n_rst(nRST),
        .edge_mode('1), //1 active high 0 active low
        .d_plus(SCK_IN_sync),
        .d_edge(sck_in_posedge)
    );

    edge_detect_spi NEGEDGE_IN
    (
        .clk(CLK),
        .n_rst(nRST),
        .edge_mode('0),
        .d_plus(SCK_IN_sync),
        .d_edge(sck_in_negedge)
    );

    always_comb begin
        sample = 0;
        data_advance = 0;
        casez({control_reg.clock_polarity, control_reg.clock_phase})
            0: begin
                sample = (control_reg.mode) ? sck_out_posedge : sck_in_posedge;
                data_advance = (control_reg.mode) ? sck_out_negedge : sck_in_negedge;
            end

            1: begin
                sample = (control_reg.mode) ? sck_out_negedge : sck_in_negedge;
                data_advance = (control_reg.mode) ? sck_out_posedge : sck_in_posedge;
            end

            2: begin
                sample = (control_reg.mode) ? sck_out_negedge : sck_in_negedge;
                data_advance = (control_reg.mode) ? sck_out_posedge : sck_in_posedge;
            end

            3: begin
                sample = (control_reg.mode) ? sck_out_posedge : sck_in_posedge;
                data_advance = (control_reg.mode) ? sck_out_negedge : sck_in_negedge;
            end
        endcase

    end

    // 8-bit data SR, re-timing FF is below
    flex_sr_spi
    #(
        .NUM_BITS(8)
    ) SR
    (
        .clk(CLK),
        .n_rst(nRST),

        //Shift Register Control Signals
        .shift_msb(control_reg.msb_first),	
        .shift_enable(shifter_en),
        .shift_clk(sample),
        .shift_clear(shifter_rst),
        .load_enable(TX_REN),
        .mode(1'b0), // mode = 0 corresponds to serial-in serial-out shift register
        .serial_in,
        .parallel_in,
        .parallel_out, 
        .serial_out
    );


    counters CNT
    (
        .clk(CLK),
        .n_rst(nRST),
        .clear(cnt_clear),
        .count_enable(count_enable),
        .count_clk(sample),
        .bytelen(byte_length_reg),
        .OPC(OPC),
        .w_done(w_done)
    );

    controller CTRL
    (
        .CLK(CLK), 
        .nRST(nRST),
        .mode(control_reg.mode),
        .EN(EN),
        .op_complete(OPC),
        .w_done(w_done),
        .SS_IN(SS_IN_sync),
        .SS_OUT(SS_OUT),
        .shifter_en(shifter_en),
        .shifter_load(load_enable),
        .counter_en(count_enable),
        .shifter_rst(shifter_rst),
        .counter_rst(cnt_clear),
        .TX_REN(TX_REN), 
        .RX_WEN(RX_WEN)
    );

    fifo # 
    (
        .NUM_BITS(8),
        .buffer_size(32), 
        .addr_bits(6),
        .WATER_DIR(1) // Watermark on nelem <= watermark
    ) FIFO_TX
    (
        .CLK(CLK), 
        .nRST(nRST),

        //Enable Signals
        .WEN(w_en[TX_DATA_REG]), //When the SPI Transmit Data Register is written to by the APB Slave Interface, the transmit FIFO will be written to by the APB Slave Interface aswell.
        .REN(TX_REN), //From the controller and dictates when to write the data from the transmit FIFO into the transmit shift register.

        //Data Signals
        .wdata(apb_data[7:0]), //From the APB Slave Interface. When the APB Slave Interface performs a write to the SPI Transmit Data Register, the data will also be written to the transmit FIFO.
        .rdata(parallel_in), //To the transmit shift register's parallel input.

        //Status Signals
        .numdata(buff_tx_numdata),
        .empty(buffer_tx_empty),
        .full(buffer_tx_full),
        .half(buffer_tx_half),
        .watermark(control_reg.tx_water_mark == 0 ? 5'd16 : control_reg.tx_water_mark)
    );

    fifo # 
    (
        .NUM_BITS(8),
        .buffer_size(32), 
        .addr_bits(6),
        .WATER_DIR(0) // Watermark on nelem >= watermark
    ) FIFO_RX
    (
        .CLK(CLK), 
        .nRST(nRST),

        //Enable Signals
        .WEN(RX_WEN), //From the controller and dictates when to read the data from the recieve shift register into the recieve FIFO.
        .REN(r_en[RX_DATA_REG]), //When the SPI Recieve Data Register is being accessed by the APB Slave Interface, the recieve FIFO's output will be read into the SPI Recieve Data Register and the APB Slave Interface.

        //Data Signals
        .wdata(parallel_out), //From the recieve shift register's parallel output.
        .rdata(fifo_rx_rdata), //To the SPI's Recieve Data Register.

        //Status Signals
        .numdata(buff_rx_numdata),
        .empty(buffer_rx_empty),
        .full(buffer_rx_full),
        .half(buffer_rx_half),
        .watermark(control_reg.rx_water_mark == 0 ? 5'd16 : control_reg.rx_water_mark)
    );

    //Temporary Assignment... Not sure if to include the conditional statement or not.
    assign r_en = /*apbif.PENABLE ? '0 : */r_enable;
    assign w_en = /*apbif.PENABLE ? '0 : */w_enable;

    // Writing to the lower 5 bits of the SR will clear the interrupts with a 1-bit
    // in their respective slot. 
    assign interrupt_clear = (w_enable[5]) ? apb_data[5:0] : '0;

    always_comb begin : REG_UPD
        control_reg_n = control_reg;
        status_reg_n = status_reg;
        byte_length_reg_n = byte_length_reg;
        baud_rate_reg_n = baud_rate_reg;

        // HW-Cleared start bit
        if(EN) begin
            control_reg_n.start_transaction = '0;
        end

        // APB Writes -- TX/RX writes routed directly, SR cannot be written.
        casez(w_enable)
            6'b000001: control_reg_n = spi_cr_t'(apb_data);
            6'b000010: byte_length_reg_n = apb_data;
            6'b000100: baud_rate_reg_n = apb_data;
        endcase

        // Status Register Updates
        status_reg_n.rx_buffer_cnt = buff_rx_numdata;
        status_reg_n.tx_buffer_cnt = buff_tx_numdata;
        status_reg_n.rx_buffer_full = buffer_rx_full;
        status_reg_n.tx_buffer_empty = buffer_tx_empty;
        status_reg_n.rx_water_mark_hit = buffer_rx_half;
        status_reg_n.tx_water_mark_hit = buffer_tx_half;

        // Detect MODF condition -- slave mode trying to output on SS line
        if(control_reg.mode == '0 && control_reg.modf_enable && control_reg.ssoe) begin
            status_reg_n.modf = '1;
        end else begin
            status_reg_n.modf = '0;
        end


        // Clear 'transfer complete' once it has been read by SW
        if(OPC) begin
            status_reg_n.transfer_complete = '1;
        end else if(r_enable[STATUS_REG]) begin
            status_reg_n.transfer_complete = '0;
        end

    end : REG_UPD

    //Internal Register Logic
    always_ff @(posedge CLK, negedge nRST) 
    begin
        if(nRST == 0) begin
            control_reg <= '{default:'0};
            byte_length_reg <= '0;
            baud_rate_reg <= '0;
            status_reg <= '0;
        end else begin
            control_reg <= control_reg_n;
            byte_length_reg <= byte_length_reg_n;
            baud_rate_reg <= baud_rate_reg_n;
            status_reg <= status_reg_n;
        end	 
    end

    // Latch the start in EN to allow transaction to proceed
    always_ff @(posedge CLK,negedge nRST) begin
        if(nRST == 0) begin
            EN <= 0;
        end else begin
            if (OPC) begin
                EN <= 0;
            // Detect a write to the 'start' bit
            end else if(w_en[CONTROL_REG] && apb_data[SPE] == 1 && status_reg.modf == 0) begin
                EN <= 1;
            end else if (status_reg.modf == 1) begin
                EN <= 0;
            end /*else if(EN && control_reg.mode == 0 && SS_IN_sync) begin
                EN <= 0; // Early exit condition
            end*/
        end
    end

    // Re-time on negative edge for output changes
    always_ff @(posedge CLK, negedge nRST) begin
        if(!nRST) begin
            retime <= '0;
            start_retime <= '0;
        end else begin
            if(data_advance || start_retime) begin
                retime <= serial_out;
            end else begin
                retime <= retime;
            end
            start_retime <= control_reg.start_transaction;  // delays retime start by one cycle so that it latches serial_out once data is loaded into SR
        end
    end

    sync_high SYNC_SCK(
        .clk(CLK),
        .n_rst(nRST),
        .async_in(spiif.SCK_IN),
        .sync_out(SCK_IN_sync)
    );

    sync_high SYNC_SS(
        .clk(CLK),
        .n_rst(nRST),
        .async_in(spiif.SS_IN),
        .sync_out(SS_IN_sync)
    );

    sync_high SYNC_MISO(
        .clk(CLK),
        .n_rst(nRST),
        .async_in(spiif.MISO_IN),
        .sync_out(MISO_IN_sync)
    );

    sync_high SYNC_MOSI(
        .clk(CLK),
        .n_rst(nRST),
        .async_in(spiif.MOSI_IN),
        .sync_out(MOSI_IN_sync)
    );

    //assign SCK_unedged = control_reg.mode ? SCLK : SCK_IN_sync;
    assign spiif.SS_OUT = control_reg.ssoe ? SS_OUT : 1;

    //bidiectional pin
    assign spiif.mode = control_reg.mode;	//tri-state enable 
    assign spiif.MOSI_OUT = retime;
    assign spiif.SCK_OUT = SCLK;
    assign spiif.MISO_OUT = retime;
    assign serial_in = control_reg.mode ? MISO_IN_sync : MOSI_IN_sync;


endmodule
