# Clock
set_location_assignment PIN_Y2 -to CLOCK_50

# UART
set_location_assignment PIN_AF20 -to UART_RX
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to UART_RX
set_location_assignment PIN_AH26 -to UART_TX
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to UART_TX

# I2C
#set_location_assignment PIN_AH23 -to I2C_SCL
#set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to I2C_SCL
#set_location_assignment PIN_AG26 -to I2C_SDA
#set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to I2C_SDA

# GPIO (from io_mux)
set_location_assignment PIN_AG26 -to BOOT_PIN[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to BOOT_PIN[1]
set_location_assignment PIN_AH23 -to BOOT_PIN[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to BOOT_PIN[0]

set_location_assignment PIN_AG23 -to GPIO[31]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[31]
set_location_assignment PIN_AE20 -to GPIO[30]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[30]
set_location_assignment PIN_AF26 -to GPIO[29]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[29]
set_location_assignment PIN_AH22 -to GPIO[28]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[28]
set_location_assignment PIN_AE24 -to GPIO[27]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[27]
set_location_assignment PIN_AG22 -to GPIO[26]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[26]
set_location_assignment PIN_AE25 -to GPIO[25]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[25]
set_location_assignment PIN_AH25 -to GPIO[24]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[24]
set_location_assignment PIN_AD25 -to GPIO[23]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[23]
set_location_assignment PIN_AG25 -to GPIO[22]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[22]
set_location_assignment PIN_AD22 -to GPIO[21]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[21]
set_location_assignment PIN_AF22 -to GPIO[20]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[20]
set_location_assignment PIN_AF21 -to GPIO[19]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[19]
set_location_assignment PIN_AE22 -to GPIO[18]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[18]
set_location_assignment PIN_AC22 -to GPIO[17]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[17]
set_location_assignment PIN_AF25 -to GPIO[16]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[16]

set_location_assignment PIN_AE21 -to GPIO[15]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[15]
set_location_assignment PIN_AF24 -to GPIO[14]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[14]
set_location_assignment PIN_AF15 -to GPIO[13]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[13]
set_location_assignment PIN_AD19 -to GPIO[12]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[12]
set_location_assignment PIN_AF16 -to GPIO[11]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[11]
set_location_assignment PIN_AC19 -to GPIO[10]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[10]
set_location_assignment PIN_AE15 -to GPIO[9]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[9]
set_location_assignment PIN_AD15 -to GPIO[8]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[8]
set_location_assignment PIN_AE16 -to GPIO[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[7]
set_location_assignment PIN_AD21 -to GPIO[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[6]
set_location_assignment PIN_Y16 -to GPIO[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[5]
set_location_assignment PIN_AC21 -to GPIO[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[4]
set_location_assignment PIN_Y17 -to GPIO[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[3]
set_location_assignment PIN_AB21 -to GPIO[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[2]
set_location_assignment PIN_AC15 -to GPIO[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[1]
set_location_assignment PIN_AB22 -to GPIO[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO[0]

# KEYs
set_location_assignment PIN_R24 -to KEY[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to KEY[3]
set_location_assignment PIN_N21 -to KEY[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to KEY[2]
set_location_assignment PIN_M21 -to KEY[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to KEY[1]
set_location_assignment PIN_M23 -to KEY[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to KEY[0]

# LEDs
set_location_assignment PIN_F17 -to LEDG[8]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[8]
set_location_assignment PIN_G21 -to LEDG[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[7]
set_location_assignment PIN_G22 -to LEDG[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[6]
set_location_assignment PIN_G20 -to LEDG[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[5]
set_location_assignment PIN_H21 -to LEDG[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[4]
set_location_assignment PIN_E24 -to LEDG[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[3]
set_location_assignment PIN_E25 -to LEDG[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[2]
set_location_assignment PIN_E22 -to LEDG[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[1]
set_location_assignment PIN_E21 -to LEDG[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[0]

set_location_assignment PIN_H15 -to LEDR[17]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[17]
set_location_assignment PIN_G16 -to LEDR[16]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[16]
set_location_assignment PIN_G15 -to LEDR[15]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[15]
set_location_assignment PIN_F15 -to LEDR[14]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[14]
set_location_assignment PIN_H17 -to LEDR[13]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[13]
set_location_assignment PIN_J16 -to LEDR[12]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[12]
set_location_assignment PIN_H16 -to LEDR[11]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[11]
set_location_assignment PIN_J15 -to LEDR[10]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[10]
set_location_assignment PIN_G17 -to LEDR[9]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[9]
set_location_assignment PIN_J17 -to LEDR[8]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[8]
set_location_assignment PIN_H19 -to LEDR[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[7]
set_location_assignment PIN_J19 -to LEDR[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[6]
set_location_assignment PIN_E18 -to LEDR[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[5]
set_location_assignment PIN_F18 -to LEDR[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[4]
set_location_assignment PIN_F21 -to LEDR[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[3]
set_location_assignment PIN_E19 -to LEDR[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[2]
set_location_assignment PIN_F19 -to LEDR[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[1]
set_location_assignment PIN_G19 -to LEDR[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[0]

set_location_assignment PIN_P5 -to altera_reserved_tck
set_location_assignment PIN_P7 -to altera_reserved_tdi
set_location_assignment PIN_P6 -to altera_reserved_tdo
set_location_assignment PIN_P8 -to altera_reserved_tms
