# Clock
set_location_assignment PIN_Y2 -to CLOCK_50

# GPIO (to/from mem controller)
# G
set_location_assignment PIN_AB22 -to addr[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[6]
set_location_assignment PIN_AB21 -to addr[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[5]
set_location_assignment PIN_AC21 -to n_WE[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to n_WE[1]

# E
set_location_assignment PIN_AD21 -to wire_data[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[6]
set_location_assignment PIN_AD15 -to wire_data[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[5]
set_location_assignment PIN_AC19 -to wire_data[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[4]
set_location_assignment PIN_AD19 -to wire_data[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[3]
set_location_assignment PIN_AF24 -to wire_data[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[2]

# C
set_location_assignment PIN_AF25 -to wire_data[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[1]
set_location_assignment PIN_AE22 -to wire_data[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[0]
set_location_assignment PIN_AF22 -to n_CE[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to n_CE[1]
set_location_assignment PIN_AG25 -to addr[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[4]
set_location_assignment PIN_AH25 -to addr[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[3]

# A
set_location_assignment PIN_AG22 -to addr[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[2]
set_location_assignment PIN_AH22 -to addr[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[1]
set_location_assignment PIN_AE20 -to addr[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[0]
set_location_assignment PIN_AF20 -to n_WE[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to n_WE[0]
set_location_assignment PIN_AH23 -to n_CE[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to n_CE[0]

# H
set_location_assignment PIN_AC15 -to addr[9]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[9]
set_location_assignment PIN_Y17 -to addr[8]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[8]
set_location_assignment PIN_Y16 -to addr[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[7]

# F
set_location_assignment PIN_AE16 -to wire_data[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[7]
set_location_assignment PIN_AE15 -to wire_data[8]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[8]
set_location_assignment PIN_AF16 -to wire_data[9]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[9]
set_location_assignment PIN_AF15 -to wire_data[10]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[10]
set_location_assignment PIN_AE21 -to wire_data[11]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[11]

# D
set_location_assignment PIN_AC22 -to wire_data[12]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[12]
set_location_assignment PIN_AF21 -to wire_data[13]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[13]
set_location_assignment PIN_AD22 -to wire_data[14]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[14]
set_location_assignment PIN_AD25 -to wire_data[15]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to wire_data[15]
set_location_assignment PIN_AE25 -to n_LB[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to n_LB[1]

# B
set_location_assignment PIN_AE24 -to n_UB[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to n_UB[1]
set_location_assignment PIN_AF26 -to n_OE[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to n_OE[1]
set_location_assignment PIN_AG23 -to n_LB[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to n_LB[0]
set_location_assignment PIN_AH26 -to n_UB[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to n_UB[0]
set_location_assignment PIN_AG26 -to n_OE[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to n_OE[0]

# Expanded IO
set_location_assignment PIN_J10 -to BOOT_PIN[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to BOOT_PIN[1]
set_location_assignment PIN_J14 -to BOOT_PIN[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to BOOT_PIN[0]
# set_location_assignment PIN_J10 -to addr[10]
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[10]
# set_location_assignment PIN_J14 -to addr[11]
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[11]
# set_location_assignment PIN_H13 -to addr[12]
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[12]
# set_location_assignment PIN_H14 -to addr[13]
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[13]
# set_location_assignment PIN_F14 -to addr[14]
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[14]
# set_location_assignment PIN_E10 -to addr[15]
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[15]
# set_location_assignment PIN_D9 -to addr[16]
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to addr[16]

# KEYs
set_location_assignment PIN_R24 -to KEY[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to KEY[3]
set_location_assignment PIN_N21 -to KEY[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to KEY[2]
set_location_assignment PIN_M21 -to KEY[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to KEY[1]
set_location_assignment PIN_M23 -to KEY[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to KEY[0]

# LEDs
set_location_assignment PIN_F17 -to LEDG[8]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[8]
set_location_assignment PIN_G21 -to LEDG[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[7]
set_location_assignment PIN_G22 -to LEDG[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[6]
set_location_assignment PIN_G20 -to LEDG[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[5]
set_location_assignment PIN_H21 -to LEDG[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[4]
set_location_assignment PIN_E24 -to LEDG[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[3]
set_location_assignment PIN_E25 -to LEDG[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[2]
set_location_assignment PIN_E22 -to LEDG[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[1]
set_location_assignment PIN_E21 -to LEDG[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDG[0]

set_location_assignment PIN_H15 -to LEDR[17]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[17]
set_location_assignment PIN_G16 -to LEDR[16]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[16]
set_location_assignment PIN_G15 -to LEDR[15]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[15]
set_location_assignment PIN_F15 -to LEDR[14]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[14]
set_location_assignment PIN_H17 -to LEDR[13]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[13]
set_location_assignment PIN_J16 -to LEDR[12]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[12]
set_location_assignment PIN_H16 -to LEDR[11]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[11]
set_location_assignment PIN_J15 -to LEDR[10]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[10]
set_location_assignment PIN_G17 -to LEDR[9]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[9]
set_location_assignment PIN_J17 -to LEDR[8]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[8]
set_location_assignment PIN_H19 -to LEDR[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[7]
set_location_assignment PIN_J19 -to LEDR[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[6]
set_location_assignment PIN_E18 -to LEDR[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[5]
set_location_assignment PIN_F18 -to LEDR[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[4]
set_location_assignment PIN_F21 -to LEDR[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[3]
set_location_assignment PIN_E19 -to LEDR[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[2]
set_location_assignment PIN_F19 -to LEDR[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[1]
set_location_assignment PIN_G19 -to LEDR[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to LEDR[0]

set_location_assignment PIN_P5 -to altera_reserved_tck
set_location_assignment PIN_P7 -to altera_reserved_tdi
set_location_assignment PIN_P6 -to altera_reserved_tdo
set_location_assignment PIN_P8 -to altera_reserved_tms
