name: AFT Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Setup and Build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/falcontron/socet-template-ci:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check tool versions
        run: |
          verilator --version
          fusesoc --version
          python3 --version

      - name: Run setup
        run: |
          export PYTHONPATH=""
          ./setup.sh

      - name: Run build
        run: |
          export PYTHONPATH=""
          ./build.sh