name: AFT Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Verible Lint
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/falcontron/socet-template-ci:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check Verible version
        run: |
          verible-verilog-lint --version

      - name: Run Verible lint
        continue-on-error: true # JUST TEMP
        run: |
          ./lint.sh